config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
	
	

	@articles=Article.all
	if params[:content].present?
		@articles=@articles.where(:content =="0")
	end
	if params[:content].present?
		@articles=@articles.where(:content =="1")
	end
	
	
	end
	def new
		@article=Article.new
		
	end
	def create
		@article=Article.new(article_params)
		if @article.save
			redirect_to root_path
		else
			render:new
		end
		
	end
	def todo
		@article=Article.find(params[:id])

		
	end
	def done

		
	end
	def edit
		@article=Article.find(params[:id])

			
	end
		def update
			@article=Article.find(params[:id])
			if @article.update(article_params)
				redirect_to root_path
		else
			render :edit
			
		end
	end
	def done
		
	end
	def todo
		
	end
	def destroy
		@article=Article.find(params[:id])
		@article.destroy
		redirect_to root_path
	end
	private
	def article_params
		params.require(:article).permit(:title,:content)
		
	end

	
end
	

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/done.html.erb
<h2>view articles</h2>
<br>
<h3>course name:<%=@article.title%></h3>
<br>
<p>
teacher:<%=@article.content%>
</p>
<br>
<p>
	time:<%=@article.coursetime%>
</p>

app/views/articles/edit.html.erb
<h2>edit article</h2>

<%= form_for @article do|f|%>
	<br>
	   edit your done or todo :<%=f.text_field :title %>
	
	<%=f.submit%>
	<%end%>

app/views/articles/index.html.erb
<h2>todo</h2>

<%=form_tag articles_path,method:"get" do%>
<%=hidden_field_tag :content ,0%>


<%=submit_tag "todo"%>
<% end %>

<%=form_tag articles_path,method:"get" do%>
<%=hidden_field_tag :content,1%>

<%=submit_tag "done"%>
<% end %>


<% @articles.each do|article|%>

	<%=  article.title %>
	<%= link_to "edit article", edit_article_path(article)%>
	<%= link_to "delete article", article_path(article),method:"delete"%>
	
	
	<br>
	<%end%>
	

app/views/articles/new.html.erb
<h2>add new article</h2>


<%= form_for @article do|f|%>
	<br>
	add todo<%=f.text_field :title %>
	<br>
	
	<%=f.submit%>
	<%end%>

app/views/articles/show.html.erb
<h2>view articles</h2>
<br>
<h3>course name:<%=@article.title%></h3>
<br>
<p>
teacher:<%=@article.content%>
</p>
<br>
<p>
	time:<%=@article.coursetime%>
</p>

app/views/home/index.html.erb
<h2>hello rails</h2>
<%= link_to "add todo" , new_article_path%>
<%= link_to " list" , articles_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>